server:
  port: 8081

spring:
  jackson:
    time-zone: UTC
  application:
    name: scrapper
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
    enabled: true

app:
  scheduler:
      interval: 1m
      batch-size: 100
      parallelism: 4
  bot:
    base-url: http://localhost:8080
  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
    base-url: https://api.stackexchange.com/2.3
    site: stackoverflow
    filter: withbody
  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN}
    per-page: 100
    issues-state: all
    issues-sort: created
    issues-direction: desc
  database:
    access-type: ${ACCESS_TYPE:SQL}
  notification:
    preview-length: 200

