CREATE TABLE links (
    id BIGSERIAL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    last_check_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
